ValueSet: PassportNSVS
Id: passport-NS-VS
Description: "Číselník jmenných prostorů pasů"
* ^meta.profile = "http://hl7.org/fhir/StructureDefinition/shareablevalueset"
* ^title = "Standardní jmenné prostory pro cestovní pasy"
* ^url = "https://ncez.mzcr.cz/standards/fhir/ValueSet/PassportNS-vs"
* ^version = "1.0.0"
* ^status = #draft
* ^experimental = false
* ^date = "2023-01-01"
* ^publisher = "NCEZ"
//* ^language = #cs
* insert SetFmmandStatusRule(1, draft)

* $uri#http://hl7.org/fhir/sid/passport-AFG "Pas: Afghanistan"
* $uri#http://hl7.org/fhir/sid/passport-ALB "Pas: Albania"
* $uri#http://hl7.org/fhir/sid/passport-DZA "Pas: Algeria"
* $uri#http://hl7.org/fhir/sid/passport-ASM "Pas: American Samoa"
* $uri#http://hl7.org/fhir/sid/passport-AND "Pas: Andorra"
* $uri#http://hl7.org/fhir/sid/passport-AGO "Pas: Angola"
* $uri#http://hl7.org/fhir/sid/passport-AIA "Pas: Anguilla"
* $uri#http://hl7.org/fhir/sid/passport-ATA "Pas: Antarctica"
* $uri#http://hl7.org/fhir/sid/passport-ATG "Pas: Antigua and Barbuda"
* $uri#http://hl7.org/fhir/sid/passport-ARG "Pas: Argentina"
* $uri#http://hl7.org/fhir/sid/passport-ARM "Pas: Armenia"
* $uri#http://hl7.org/fhir/sid/passport-ABW "Pas: Aruba"
* $uri#http://hl7.org/fhir/sid/passport-AUS "Pas: Australia"
* $uri#http://hl7.org/fhir/sid/passport-AUT "Pas: Austria"
* $uri#http://hl7.org/fhir/sid/passport-AZE "Pas: Azerbaijan"
* $uri#http://hl7.org/fhir/sid/passport-BHS "Pas: Bahamas (the)"
* $uri#http://hl7.org/fhir/sid/passport-BHR "Pas: Bahrain"
* $uri#http://hl7.org/fhir/sid/passport-BGD "Pas: Bangladesh"
* $uri#http://hl7.org/fhir/sid/passport-BRB "Pas: Barbados"
* $uri#http://hl7.org/fhir/sid/passport-BLR "Pas: Belarus"
* $uri#http://hl7.org/fhir/sid/passport-BEL "Pas: Belgium"
* $uri#http://hl7.org/fhir/sid/passport-BLZ "Pas: Belize"
* $uri#http://hl7.org/fhir/sid/passport-BEN "Pas: Benin"
* $uri#http://hl7.org/fhir/sid/passport-BMU "Pas: Bermuda"
* $uri#http://hl7.org/fhir/sid/passport-BTN "Pas: Bhutan"
* $uri#http://hl7.org/fhir/sid/passport-BOL "Pas: Bolivia (Plurinational State of)"
* $uri#http://hl7.org/fhir/sid/passport-BES "Pas: Bonaire, Sint Eustatius and Saba"
* $uri#http://hl7.org/fhir/sid/passport-BIH "Pas: Bosnia and Herzegovina"
* $uri#http://hl7.org/fhir/sid/passport-BWA "Pas: Botswana"
* $uri#http://hl7.org/fhir/sid/passport-BVT "Pas: Bouvet Island"
* $uri#http://hl7.org/fhir/sid/passport-BRA "Pas: Brazil"
* $uri#http://hl7.org/fhir/sid/passport-IOT "Pas: British Indian Ocean Territory (the)"
* $uri#http://hl7.org/fhir/sid/passport-BRN "Pas: Brunei Darussalam"
* $uri#http://hl7.org/fhir/sid/passport-BGR "Pas: Bulgaria"
* $uri#http://hl7.org/fhir/sid/passport-BFA "Pas: Burkina Faso"
* $uri#http://hl7.org/fhir/sid/passport-BDI "Pas: Burundi"
* $uri#http://hl7.org/fhir/sid/passport-CPV "Pas: Cabo Verde"
* $uri#http://hl7.org/fhir/sid/passport-KHM "Pas: Cambodia"
* $uri#http://hl7.org/fhir/sid/passport-CMR "Pas: Cameroon"
* $uri#http://hl7.org/fhir/sid/passport-CAN "Pas: Canada"
* $uri#http://hl7.org/fhir/sid/passport-CYM "Pas: Cayman Islands (the)"
* $uri#http://hl7.org/fhir/sid/passport-CAF "Pas: Central African Republic (the)"
* $uri#http://hl7.org/fhir/sid/passport-TCD "Pas: Chad"
* $uri#http://hl7.org/fhir/sid/passport-CHL "Pas: Chile"
* $uri#http://hl7.org/fhir/sid/passport-CHN "Pas: China"
* $uri#http://hl7.org/fhir/sid/passport-CXR "Pas: Christmas Island"
* $uri#http://hl7.org/fhir/sid/passport-CCK "Pas: Cocos (Keeling) Islands (the)"
* $uri#http://hl7.org/fhir/sid/passport-COL "Pas: Colombia"
* $uri#http://hl7.org/fhir/sid/passport-COM "Pas: Comoros (the)"
* $uri#http://hl7.org/fhir/sid/passport-COD "Pas: Congo (the Democratic Republic of the)"
* $uri#http://hl7.org/fhir/sid/passport-COG "Pas: Congo (the)"
* $uri#http://hl7.org/fhir/sid/passport-COK "Pas: Cook Islands (the)"
* $uri#http://hl7.org/fhir/sid/passport-CRI "Pas: Costa Rica"
* $uri#http://hl7.org/fhir/sid/passport-HRV "Pas: Croatia"
* $uri#http://hl7.org/fhir/sid/passport-CUB "Pas: Cuba"
* $uri#http://hl7.org/fhir/sid/passport-CUW "Pas: Curaçao"
* $uri#http://hl7.org/fhir/sid/passport-CYP "Pas: Cyprus"
* $uri#http://hl7.org/fhir/sid/passport-CZE "Pas: Czechia"
* $uri#http://hl7.org/fhir/sid/passport-CIV "Pas: Côte d'Ivoire"
* $uri#http://hl7.org/fhir/sid/passport-DNK "Pas: Denmark"
* $uri#http://hl7.org/fhir/sid/passport-DJI "Pas: Djibouti"
* $uri#http://hl7.org/fhir/sid/passport-DMA "Pas: Dominica"
* $uri#http://hl7.org/fhir/sid/passport-DOM "Pas: Dominican Republic (the)"
* $uri#http://hl7.org/fhir/sid/passport-ECU "Pas: Ecuador"
* $uri#http://hl7.org/fhir/sid/passport-EGY "Pas: Egypt"
* $uri#http://hl7.org/fhir/sid/passport-SLV "Pas: El Salvador"
* $uri#http://hl7.org/fhir/sid/passport-GNQ "Pas: Equatorial Guinea"
* $uri#http://hl7.org/fhir/sid/passport-ERI "Pas: Eritrea"
* $uri#http://hl7.org/fhir/sid/passport-EST "Pas: Estonia"
* $uri#http://hl7.org/fhir/sid/passport-SWZ "Pas: Eswatini"
* $uri#http://hl7.org/fhir/sid/passport-ETH "Pas: Ethiopia"
* $uri#http://hl7.org/fhir/sid/passport-FLK "Pas: Falkland Islands (the) [Malvinas]"
* $uri#http://hl7.org/fhir/sid/passport-FRO "Pas: Faroe Islands (the)"
* $uri#http://hl7.org/fhir/sid/passport-FJI "Pas: Fiji"
* $uri#http://hl7.org/fhir/sid/passport-FIN "Pas: Finland"
* $uri#http://hl7.org/fhir/sid/passport-FRA "Pas: France"
* $uri#http://hl7.org/fhir/sid/passport-GUF "Pas: French Guiana"
* $uri#http://hl7.org/fhir/sid/passport-PYF "Pas: French Polynesia"
* $uri#http://hl7.org/fhir/sid/passport-ATF "Pas: French Southern Territories (the)"
* $uri#http://hl7.org/fhir/sid/passport-GAB "Pas: Gabon"
* $uri#http://hl7.org/fhir/sid/passport-GMB "Pas: Gambia (the)"
* $uri#http://hl7.org/fhir/sid/passport-GEO "Pas: Georgia"
* $uri#http://hl7.org/fhir/sid/passport-DEU "Pas: Germany"
* $uri#http://hl7.org/fhir/sid/passport-GHA "Pas: Ghana"
* $uri#http://hl7.org/fhir/sid/passport-GIB "Pas: Gibraltar"
* $uri#http://hl7.org/fhir/sid/passport-GRC "Pas: Greece"
* $uri#http://hl7.org/fhir/sid/passport-GRL "Pas: Greenland"
* $uri#http://hl7.org/fhir/sid/passport-GRD "Pas: Grenada"
* $uri#http://hl7.org/fhir/sid/passport-GLP "Pas: Guadeloupe"
* $uri#http://hl7.org/fhir/sid/passport-GUM "Pas: Guam"
* $uri#http://hl7.org/fhir/sid/passport-GTM "Pas: Guatemala"
* $uri#http://hl7.org/fhir/sid/passport-GGY "Pas: Guernsey"
* $uri#http://hl7.org/fhir/sid/passport-GIN "Pas: Guinea"
* $uri#http://hl7.org/fhir/sid/passport-GNB "Pas: Guinea-Bissau"
* $uri#http://hl7.org/fhir/sid/passport-GUY "Pas: Guyana"
* $uri#http://hl7.org/fhir/sid/passport-HTI "Pas: Haiti"
* $uri#http://hl7.org/fhir/sid/passport-HMD "Pas: Heard Island and McDonald Islands"
* $uri#http://hl7.org/fhir/sid/passport-VAT "Pas: Holy See (the)"
* $uri#http://hl7.org/fhir/sid/passport-HND "Pas: Honduras"
* $uri#http://hl7.org/fhir/sid/passport-HKG "Pas: Hong Kong"
* $uri#http://hl7.org/fhir/sid/passport-HUN "Pas: Hungary"
* $uri#http://hl7.org/fhir/sid/passport-ISL "Pas: Iceland"
* $uri#http://hl7.org/fhir/sid/passport-IND "Pas: India"
* $uri#http://hl7.org/fhir/sid/passport-IDN "Pas: Indonesia"
* $uri#http://hl7.org/fhir/sid/passport-IRN "Pas: Iran (Islamic Republic of)"
* $uri#http://hl7.org/fhir/sid/passport-IRQ "Pas: Iraq"
* $uri#http://hl7.org/fhir/sid/passport-IRL "Pas: Ireland"
* $uri#http://hl7.org/fhir/sid/passport-IMN "Pas: Isle of Man"
* $uri#http://hl7.org/fhir/sid/passport-ISR "Pas: Israel"
* $uri#http://hl7.org/fhir/sid/passport-ITA "Pas: Italy"
* $uri#http://hl7.org/fhir/sid/passport-JAM "Pas: Jamaica"
* $uri#http://hl7.org/fhir/sid/passport-JPN "Pas: Japan"
* $uri#http://hl7.org/fhir/sid/passport-JEY "Pas: Jersey"
* $uri#http://hl7.org/fhir/sid/passport-JOR "Pas: Jordan"
* $uri#http://hl7.org/fhir/sid/passport-KAZ "Pas: Kazakhstan"
* $uri#http://hl7.org/fhir/sid/passport-KEN "Pas: Kenya"
* $uri#http://hl7.org/fhir/sid/passport-KIR "Pas: Kiribati"
* $uri#http://hl7.org/fhir/sid/passport-PRK "Pas: Korea (the Democratic People's Republic of)"
* $uri#http://hl7.org/fhir/sid/passport-KOR "Pas: Korea (the Republic of)"
* $uri#http://hl7.org/fhir/sid/passport-KWT "Pas: Kuwait"
* $uri#http://hl7.org/fhir/sid/passport-KGZ "Pas: Kyrgyzstan"
* $uri#http://hl7.org/fhir/sid/passport-LAO "Pas: Lao People's Democratic Republic (the)"
* $uri#http://hl7.org/fhir/sid/passport-LVA "Pas: Latvia"
* $uri#http://hl7.org/fhir/sid/passport-LBN "Pas: Lebanon"
* $uri#http://hl7.org/fhir/sid/passport-LSO "Pas: Lesotho"
* $uri#http://hl7.org/fhir/sid/passport-LBR "Pas: Liberia"
* $uri#http://hl7.org/fhir/sid/passport-LBY "Pas: Libya"
* $uri#http://hl7.org/fhir/sid/passport-LIE "Pas: Liechtenstein"
* $uri#http://hl7.org/fhir/sid/passport-LTU "Pas: Lithuania"
* $uri#http://hl7.org/fhir/sid/passport-LUX "Pas: Luxembourg"
* $uri#http://hl7.org/fhir/sid/passport-MAC "Pas: Macao"
* $uri#http://hl7.org/fhir/sid/passport-MDG "Pas: Madagascar"
* $uri#http://hl7.org/fhir/sid/passport-MWI "Pas: Malawi"
* $uri#http://hl7.org/fhir/sid/passport-MYS "Pas: Malaysia"
* $uri#http://hl7.org/fhir/sid/passport-MDV "Pas: Maldives"
* $uri#http://hl7.org/fhir/sid/passport-MLI "Pas: Mali"
* $uri#http://hl7.org/fhir/sid/passport-MLT "Pas: Malta"
* $uri#http://hl7.org/fhir/sid/passport-MHL "Pas: Marshall Islands (the)"
* $uri#http://hl7.org/fhir/sid/passport-MTQ "Pas: Martinique"
* $uri#http://hl7.org/fhir/sid/passport-MRT "Pas: Mauritania"
* $uri#http://hl7.org/fhir/sid/passport-MUS "Pas: Mauritius"
* $uri#http://hl7.org/fhir/sid/passport-MYT "Pas: Mayotte"
* $uri#http://hl7.org/fhir/sid/passport-MEX "Pas: Mexico"
* $uri#http://hl7.org/fhir/sid/passport-FSM "Pas: Micronesia (Federated States of)"
* $uri#http://hl7.org/fhir/sid/passport-MDA "Pas: Moldova (the Republic of)"
* $uri#http://hl7.org/fhir/sid/passport-MCO "Pas: Monaco"
* $uri#http://hl7.org/fhir/sid/passport-MNG "Pas: Mongolia"
* $uri#http://hl7.org/fhir/sid/passport-MNE "Pas: Montenegro"
* $uri#http://hl7.org/fhir/sid/passport-MSR "Pas: Montserrat"
* $uri#http://hl7.org/fhir/sid/passport-MAR "Pas: Morocco"
* $uri#http://hl7.org/fhir/sid/passport-MOZ "Pas: Mozambique"
* $uri#http://hl7.org/fhir/sid/passport-MMR "Pas: Myanmar"
* $uri#http://hl7.org/fhir/sid/passport-NAM "Pas: Namibia"
* $uri#http://hl7.org/fhir/sid/passport-NRU "Pas: Nauru"
* $uri#http://hl7.org/fhir/sid/passport-NPL "Pas: Nepal"
* $uri#http://hl7.org/fhir/sid/passport-NLD "Pas: Netherlands (Kingdom of the)"
* $uri#http://hl7.org/fhir/sid/passport-NCL "Pas: New Caledonia"
* $uri#http://hl7.org/fhir/sid/passport-NZL "Pas: New Zealand"
* $uri#http://hl7.org/fhir/sid/passport-NIC "Pas: Nicaragua"
* $uri#http://hl7.org/fhir/sid/passport-NER "Pas: Niger (the)"
* $uri#http://hl7.org/fhir/sid/passport-NGA "Pas: Nigeria"
* $uri#http://hl7.org/fhir/sid/passport-NIU "Pas: Niue"
* $uri#http://hl7.org/fhir/sid/passport-NFK "Pas: Norfolk Island"
* $uri#http://hl7.org/fhir/sid/passport-MKD "Pas: North Macedonia"
* $uri#http://hl7.org/fhir/sid/passport-MNP "Pas: Northern Mariana Islands (the)"
* $uri#http://hl7.org/fhir/sid/passport-NOR "Pas: Norway"
* $uri#http://hl7.org/fhir/sid/passport-OMN "Pas: Oman"
* $uri#http://hl7.org/fhir/sid/passport-PAK "Pas: Pakistan"
* $uri#http://hl7.org/fhir/sid/passport-PLW "Pas: Palau"
* $uri#http://hl7.org/fhir/sid/passport-PSE "Pas: Palestine, State of"
* $uri#http://hl7.org/fhir/sid/passport-PAN "Pas: Panama"
* $uri#http://hl7.org/fhir/sid/passport-PNG "Pas: Papua New Guinea"
* $uri#http://hl7.org/fhir/sid/passport-PRY "Pas: Paraguay"
* $uri#http://hl7.org/fhir/sid/passport-PER "Pas: Peru"
* $uri#http://hl7.org/fhir/sid/passport-PHL "Pas: Philippines (the)"
* $uri#http://hl7.org/fhir/sid/passport-PCN "Pas: Pitcairn"
* $uri#http://hl7.org/fhir/sid/passport-POL "Pas: Poland"
* $uri#http://hl7.org/fhir/sid/passport-PRT "Pas: Portugal"
* $uri#http://hl7.org/fhir/sid/passport-PRI "Pas: Puerto Rico"
* $uri#http://hl7.org/fhir/sid/passport-QAT "Pas: Qatar"
* $uri#http://hl7.org/fhir/sid/passport-ROU "Pas: Romania"
* $uri#http://hl7.org/fhir/sid/passport-RUS "Pas: Russian Federation (the)"
* $uri#http://hl7.org/fhir/sid/passport-RWA "Pas: Rwanda"
* $uri#http://hl7.org/fhir/sid/passport-REU "Pas: Réunion"
* $uri#http://hl7.org/fhir/sid/passport-BLM "Pas: Saint Barthélemy"
* $uri#http://hl7.org/fhir/sid/passport-SHN "Pas: Saint Helena, Ascension and Tristan da Cunha"
* $uri#http://hl7.org/fhir/sid/passport-KNA "Pas: Saint Kitts and Nevis"
* $uri#http://hl7.org/fhir/sid/passport-LCA "Pas: Saint Lucia"
* $uri#http://hl7.org/fhir/sid/passport-MAF "Pas: Saint Martin (French part)"
* $uri#http://hl7.org/fhir/sid/passport-SPM "Pas: Saint Pierre and Miquelon"
* $uri#http://hl7.org/fhir/sid/passport-VCT "Pas: Saint Vincent and the Grenadines"
* $uri#http://hl7.org/fhir/sid/passport-WSM "Pas: Samoa"
* $uri#http://hl7.org/fhir/sid/passport-SMR "Pas: San Marino"
* $uri#http://hl7.org/fhir/sid/passport-STP "Pas: Sao Tome and Principe"
* $uri#http://hl7.org/fhir/sid/passport-SAU "Pas: Saudi Arabia"
* $uri#http://hl7.org/fhir/sid/passport-SEN "Pas: Senegal"
* $uri#http://hl7.org/fhir/sid/passport-SRB "Pas: Serbia"
* $uri#http://hl7.org/fhir/sid/passport-SYC "Pas: Seychelles"
* $uri#http://hl7.org/fhir/sid/passport-SLE "Pas: Sierra Leone"
* $uri#http://hl7.org/fhir/sid/passport-SGP "Pas: Singapore"
* $uri#http://hl7.org/fhir/sid/passport-SXM "Pas: Sint Maarten (Dutch part)"
* $uri#http://hl7.org/fhir/sid/passport-SVK "Pas: Slovakia"
* $uri#http://hl7.org/fhir/sid/passport-SVN "Pas: Slovenia"
* $uri#http://hl7.org/fhir/sid/passport-SLB "Pas: Solomon Islands"
* $uri#http://hl7.org/fhir/sid/passport-SOM "Pas: Somalia"
* $uri#http://hl7.org/fhir/sid/passport-ZAF "Pas: South Africa"
* $uri#http://hl7.org/fhir/sid/passport-SGS "Pas: South Georgia and the South Sandwich Islands"
* $uri#http://hl7.org/fhir/sid/passport-SSD "Pas: South Sudan"
* $uri#http://hl7.org/fhir/sid/passport-ESP "Pas: Spain"
* $uri#http://hl7.org/fhir/sid/passport-LKA "Pas: Sri Lanka"
* $uri#http://hl7.org/fhir/sid/passport-SDN "Pas: Sudan (the)"
* $uri#http://hl7.org/fhir/sid/passport-SUR "Pas: Suriname"
* $uri#http://hl7.org/fhir/sid/passport-SJM "Pas: Svalbard and Jan Mayen"
* $uri#http://hl7.org/fhir/sid/passport-SWE "Pas: Sweden"
* $uri#http://hl7.org/fhir/sid/passport-CHE "Pas: Switzerland"
* $uri#http://hl7.org/fhir/sid/passport-SYR "Pas: Syrian Arab Republic (the)"
* $uri#http://hl7.org/fhir/sid/passport-TWN "Pas: Taiwan (Province of China)"
* $uri#http://hl7.org/fhir/sid/passport-TJK "Pas: Tajikistan"
* $uri#http://hl7.org/fhir/sid/passport-TZA "Pas: Tanzania, the United Republic of"
* $uri#http://hl7.org/fhir/sid/passport-THA "Pas: Thailand"
* $uri#http://hl7.org/fhir/sid/passport-TLS "Pas: Timor-Leste"
* $uri#http://hl7.org/fhir/sid/passport-TGO "Pas: Togo"
* $uri#http://hl7.org/fhir/sid/passport-TKL "Pas: Tokelau"
* $uri#http://hl7.org/fhir/sid/passport-TON "Pas: Tonga"
* $uri#http://hl7.org/fhir/sid/passport-TTO "Pas: Trinidad and Tobago"
* $uri#http://hl7.org/fhir/sid/passport-TUN "Pas: Tunisia"
* $uri#http://hl7.org/fhir/sid/passport-TKM "Pas: Turkmenistan"
* $uri#http://hl7.org/fhir/sid/passport-TCA "Pas: Turks and Caicos Islands (the)"
* $uri#http://hl7.org/fhir/sid/passport-TUV "Pas: Tuvalu"
* $uri#http://hl7.org/fhir/sid/passport-TUR "Pas: Türkiye"
* $uri#http://hl7.org/fhir/sid/passport-UGA "Pas: Uganda"
* $uri#http://hl7.org/fhir/sid/passport-UKR "Pas: Ukraine"
* $uri#http://hl7.org/fhir/sid/passport-ARE "Pas: United Arab Emirates (the)"
* $uri#http://hl7.org/fhir/sid/passport-GBR "Pas: United Kingdom of Great Britain and Northern Ireland (the)"
* $uri#http://hl7.org/fhir/sid/passport-UMI "Pas: United States Minor Outlying Islands (the)"
* $uri#http://hl7.org/fhir/sid/passport-USA "Pas: United States of America (the)"
* $uri#http://hl7.org/fhir/sid/passport-URY "Pas: Uruguay"
* $uri#http://hl7.org/fhir/sid/passport-UZB "Pas: Uzbekistan"
* $uri#http://hl7.org/fhir/sid/passport-VUT "Pas: Vanuatu"
* $uri#http://hl7.org/fhir/sid/passport-VEN "Pas: Venezuela (Bolivarian Republic of)"
* $uri#http://hl7.org/fhir/sid/passport-VNM "Pas: Viet Nam"
* $uri#http://hl7.org/fhir/sid/passport-VGB "Pas: Virgin Islands (British)"
* $uri#http://hl7.org/fhir/sid/passport-VIR "Pas: Virgin Islands (U.S.)"
* $uri#http://hl7.org/fhir/sid/passport-WLF "Pas: Wallis and Futuna"
* $uri#http://hl7.org/fhir/sid/passport-ESH "Pas: Western Sahara*"
* $uri#http://hl7.org/fhir/sid/passport-YEM "Pas: Yemen"
* $uri#http://hl7.org/fhir/sid/passport-ZMB "Pas: Zambia"
* $uri#http://hl7.org/fhir/sid/passport-ZWE "Pas: Zimbabwe"
* $uri#http://hl7.org/fhir/sid/passport-ALA "Pas: Åland Islands"